use std::{fmt, hash::Hash, iter::Skip};

use base::{
    arena::Interned,
    hash::{IndexSet, Map, Set},
    index::Idx,
};
use span::{Ident, Sp, Span};

use crate::{Arena, Path, WebId, NO_WEB};

/// A representation of a type during type inference.
// TODO. interning should canonicalize.
//       don't allow Ty::new(..), make it a method on a ctx.
#[derive(Clone, Copy, Debug)]
pub struct Ty<'hir>(Interned<'hir, TyKind<'hir>>, Span);

impl PartialEq for Ty<'_> {
    fn eq(&self, other: &Self) -> bool {
        self.kind() == other.kind()
    }
}

impl Eq for Ty<'_> {}

impl Hash for Ty<'_> {
    fn hash<H: std::hash::Hasher>(&self, state: &mut H) {
        // Only hash type pointer.
        self.0.hash(state);
    }
}

#[cfg(test)]
mod test {
    use super::{BaseType, TyKind};
    use crate::Arena;
    use span::{BytePos, Span};

    #[test]
    fn equality() {
        let arena = Arena::default();
        let t1 = arena.typ(TyKind::Base(BaseType::Unit), Span::from(0..1));
        let t2 = arena.typ(TyKind::Base(BaseType::Unit), Span::from(1..2));
        assert_eq!(t1, t2);
    }
}

#[derive(Clone, Copy, PartialEq, Eq, Debug)]
pub enum TyKind<'hir> {
    /// An abstract type.
    Abstract,
    /// A base/builtin type.
    Base(BaseType),

    /// Represents a unification type variable.
    /// For a successfully inferred program, these should all
    /// be substituted away.
    Uni(UniVar),
    /// Represents a type variable that comes from a user-specified
    /// type, such as the `'a` in `'a -> 'a`.
    Var(TypeVar),
    /// Skolem/rigid type variable.
    Skolem(Skolem),

    /// Type represented by a path to a type declaration,
    /// with zero or more arguments.
    App(Path<'hir>, &'hir [Ty<'hir>]),

    /// Arrow type `a -> b`.
    Arrow(WebId, Ty<'hir>, Ty<'hir>),
    /// Product of types.
    Tuple(&'hir [Ty<'hir>]),
    /// Homogeneous vector.
    Vector(Ty<'hir>),

    /// Extensible row type.
    // TODO. unimplemented.
    Row(&'hir [(Ident, Ty<'hir>)], Option<Ty<'hir>>),
}

base::newtype_index! {
    /// Unification variable generated by the elaborator/constraint generator.
    #[derive(PartialOrd, Ord)]
    pub struct UniVarId {}
}

base::newtype_index! {
    /// Unique identifier for a skolem type variable.
    #[derive(PartialOrd, Ord)]
    pub struct SkolemId {}
}

impl fmt::Display for UniVarId {
    fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
        write!(f, "'{}", self.index())
    }
}

#[derive(Clone, Copy, PartialEq, Eq, Hash, Debug)]
pub enum BaseType {
    Unit,
    Bool,
    Int32,
    Str,
}

impl fmt::Display for BaseType {
    fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
        match self {
            Self::Unit => "()",
            Self::Bool => "bool",
            Self::Int32 => "i32",
            Self::Str => "str",
        }
        .fmt(f)
    }
}

#[derive(Clone, Copy, PartialEq, Eq, Hash, Debug)]
pub struct UniVar {
    pub id: UniVarId,
    pub kind: Kind,
}

impl UniVar {
    pub fn new(id: UniVarId, kind: Kind) -> Self {
        Self { id, kind }
    }
}

impl fmt::Display for UniVar {
    fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
        write!(f, "'{}", self.id.index())
    }
}

/// A type variable coming from a user-written polymorphic type.
#[derive(Clone, Copy, PartialEq, Eq, Hash, Debug)]
pub struct TypeVar {
    pub name: Ident,
}

impl TypeVar {
    pub fn new(name: Ident) -> Self {
        Self { name }
    }
}

impl PartialOrd for TypeVar {
    fn partial_cmp(&self, other: &Self) -> Option<std::cmp::Ordering> {
        Some(self.cmp(other))
    }
}

impl Ord for TypeVar {
    fn cmp(&self, other: &Self) -> std::cmp::Ordering {
        self.name.sym.cmp(&other.name.sym)
    }
}

impl fmt::Display for TypeVar {
    fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
        self.name.fmt(f)
    }
}

/// A skolem (or "rigid") type variable.
#[derive(Clone, Copy, Debug)]
pub struct Skolem {
    pub id: SkolemId,
    pub name: Ident,
}

impl Skolem {
    pub fn new(id: SkolemId, name: Ident) -> Self {
        Self { id, name }
    }
}

impl PartialEq for Skolem {
    fn eq(&self, other: &Self) -> bool {
        self.id == other.id
    }
}

impl Eq for Skolem {}

impl PartialOrd for Skolem {
    fn partial_cmp(&self, other: &Self) -> Option<std::cmp::Ordering> {
        Some(self.cmp(other))
    }
}

impl Ord for Skolem {
    fn cmp(&self, other: &Self) -> std::cmp::Ordering {
        self.id.cmp(&other.id)
    }
}

impl fmt::Display for Skolem {
    fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
        write!(f, "#{}", self.name)
    }
}

#[derive(Clone, Copy, PartialEq, Eq, Hash, Debug)]
pub struct Kind {
    /// Kind of term types is arity(0) = *.
    /// Constructor kinds are arity(1) = * -> *, ...
    arity: usize,
}

impl Kind {
    pub fn new(arity: usize) -> Self {
        Kind { arity }
    }
}

impl fmt::Display for Kind {
    fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
        "*".fmt(f)?;
        for _ in 1..self.arity {
            " -> *".fmt(f)?;
        }
        Ok(())
    }
}

pub trait Visitor<T>: Sized {
    fn visit(&mut self, typ: T);
}

pub trait Folder<'hir, T>: Sized {
    fn arena(&self) -> &'hir Arena<'hir>;

    fn fold(&mut self, typ: T) -> T;
}

pub trait Substitutable<'hir>: Copy + PartialEq + fmt::Display {
    type Var: Idx + fmt::Display;

    fn as_var(&self) -> Option<Self::Var>;

    fn make_var(arena: &'hir Arena<'hir>, var: Self::Var) -> Self;

    fn visit_with<V>(&self, v: &mut V)
    where
        V: Visitor<Self>;

    fn fold_with<F>(self, f: &mut F) -> Self
    where
        F: Folder<'hir, Self>;
}

impl<'hir> Ty<'hir> {
    #[inline]
    pub fn new(arena: &'hir Arena<'hir>, kind: TyKind<'hir>, span: Span) -> Self {
        Ty(Interned::new_unchecked(arena.alloc(kind)), span)
    }

    #[inline]
    pub fn kind(self) -> &'hir TyKind<'hir> {
        (self.0).0
    }

    #[inline]
    pub fn span(&self) -> Span {
        self.1
    }

    pub fn visit_with<V>(&self, v: &mut V)
    where
        V: Visitor<Self>,
    {
        match *self.kind() {
            TyKind::Abstract
            | TyKind::Base(_)
            | TyKind::Var(_)
            | TyKind::Uni(_)
            | TyKind::Skolem(_) => (),
            TyKind::Vector(t) => v.visit(t),
            TyKind::Arrow(_, t1, t2) => {
                v.visit(t1);
                v.visit(t2);
            }
            TyKind::App(_, ts) | TyKind::Tuple(ts) => ts.iter().for_each(|&t| v.visit(t)),
            TyKind::Row(fields, ext) => {
                fields.iter().for_each(|&(_, t)| v.visit(t));
                if let Some(t) = ext {
                    v.visit(t);
                }
            }
        }
    }

    pub fn fold_with<F>(self, f: &mut F) -> Self
    where
        F: Folder<'hir, Self>,
    {
        let kind = match *self.kind() {
            TyKind::Abstract
            | TyKind::Base(_)
            | TyKind::Var(_)
            | TyKind::Uni(_)
            | TyKind::Skolem(_) => return self,
            TyKind::App(h, ts) => {
                TyKind::App(h, f.arena().alloc_from_iter(ts.iter().map(|&t| f.fold(t))))
            }
            TyKind::Vector(t) => TyKind::Vector(f.fold(t)),
            TyKind::Arrow(u, t1, t2) => TyKind::Arrow(u, f.fold(t1), f.fold(t2)),
            TyKind::Tuple(ts) => {
                TyKind::Tuple(f.arena().alloc_from_iter(ts.iter().map(|&t| f.fold(t))))
            }
            TyKind::Row(fields, ext) => TyKind::Row(
                f.arena()
                    .alloc_from_iter(fields.iter().map(|&(l, t)| (l, f.fold(t)))),
                ext.map(|t| f.fold(t)),
            ),
        };
        if *self.kind() == kind {
            self
        } else {
            f.arena().typ(kind, self.span())
        }
    }

    pub fn tuple<I>(arena: &'hir Arena<'hir>, iter: I, span: Span) -> Self
    where
        I: IntoIterator<Item = Self>,
    {
        arena.typ(TyKind::Tuple(arena.alloc_from_iter(iter)), span)
    }

    pub fn app<I>(arena: &'hir Arena<'hir>, head: Path<'hir>, args: I, span: Span) -> Self
    where
        I: IntoIterator<Item = Self>,
    {
        arena.typ(TyKind::App(head, arena.alloc_from_iter(args)), span)
    }

    pub fn arrow(arena: &'hir Arena<'hir>, web_id: WebId, source: Self, target: Self) -> Self {
        arena.typ(
            TyKind::Arrow(web_id, source, target),
            source.span().merge(target.span()),
        )
    }

    pub fn n_arrow<I>(arena: &'hir Arena<'hir>, sources: I, target: Self) -> Self
    where
        I: IntoIterator<Item = Self>,
        I::IntoIter: DoubleEndedIterator,
    {
        sources
            .into_iter()
            .rev()
            .fold(target, |acc, source| Ty::arrow(arena, NO_WEB, source, acc))
    }

    pub fn path(arena: &'hir Arena<'hir>, path: Path<'hir>) -> Self {
        arena.typ(TyKind::App(path, &[]), path.span())
    }

    pub fn type_var(arena: &'hir Arena<'hir>, var: TypeVar) -> Self {
        arena.typ(TyKind::Var(var), var.name.span)
    }

    pub fn uni_var(arena: &'hir Arena<'hir>, var: UniVar) -> Self {
        arena.typ(TyKind::Uni(var), Span::dummy())
    }

    pub fn skolem(arena: &'hir Arena<'hir>, skolem: Skolem) -> Self {
        arena.typ(TyKind::Skolem(skolem), skolem.name.span)
    }

    pub fn eq_alpha(&self, other: Self) -> bool {
        #[derive(Default)]
        struct VarMap {
            uni_vars: Map<UniVarId, UniVarId>,
            type_vars: Map<Ident, Ident>,
        }

        fn go<'a>(map: &mut VarMap, lhs: Ty<'a>, rhs: Ty<'a>) -> bool {
            match (*lhs.kind(), *rhs.kind()) {
                (lhs, rhs) if lhs == rhs => true,
                (TyKind::Var(l), TyKind::Var(r)) => match map.type_vars.get(&l.name) {
                    Some(id) => *id == r.name,
                    None => {
                        map.type_vars.insert(l.name, r.name);
                        true
                    }
                },
                (TyKind::Uni(l), TyKind::Uni(r)) => match map.uni_vars.get(&l.id) {
                    Some(id) => *id == r.id,
                    None => {
                        map.uni_vars.insert(l.id, r.id);
                        true
                    }
                },
                (TyKind::Arrow(_, l1, l2), TyKind::Arrow(_, r1, r2)) => {
                    go(map, l1, r1) && go(map, l2, r2)
                }
                (TyKind::Vector(l), TyKind::Vector(r)) => go(map, l, r),
                (TyKind::Tuple(ls), TyKind::Tuple(rs)) if ls.len() == rs.len() => {
                    ls.iter().zip(rs).all(|(&l, &r)| go(map, l, r))
                }
                (_, _) => false,
            }
        }

        go(&mut VarMap::default(), *self, other)
    }

    pub fn uni_vars(&self) -> IndexSet<UniVar> {
        #[derive(Default)]
        struct Vars {
            acc: IndexSet<UniVar>,
        }

        impl<'hir> Visitor<Ty<'hir>> for Vars {
            fn visit(&mut self, typ: Ty<'hir>) {
                if let TyKind::Uni(var) = typ.kind() {
                    self.acc.insert(*var);
                }
                typ.visit_with(self);
            }
        }

        let mut vars = Vars::default();
        vars.visit(*self);
        vars.acc
    }

    pub fn type_vars(&self) -> Set<TypeVar> {
        #[derive(Default)]
        struct Vars {
            acc: Set<TypeVar>,
        }

        impl<'hir> Visitor<Ty<'hir>> for Vars {
            fn visit(&mut self, typ: Ty<'hir>) {
                if let TyKind::Var(var) = typ.kind() {
                    self.acc.insert(*var);
                }
                typ.visit_with(self);
            }
        }

        let mut vars = Vars::default();
        vars.visit(*self);
        vars.acc
    }

    pub fn subst_type_var(self, arena: &'hir Arena<'hir>, subs: &Map<Ident, Self>) -> Self {
        struct Subs<'a, 'hir> {
            arena: &'hir Arena<'hir>,
            subs: &'a Map<Ident, Ty<'hir>>,
        }

        impl<'hir> Folder<'hir, Ty<'hir>> for Subs<'_, 'hir> {
            fn arena(&self) -> &'hir Arena<'hir> {
                self.arena
            }

            fn fold(&mut self, typ: Ty<'hir>) -> Ty<'hir> {
                if let TyKind::Var(var) = typ.kind()
                    && let Some(&other) = self.subs.get(&var.name)
                {
                    return other;
                }
                typ.fold_with(self)
            }
        }

        Subs { arena, subs }.fold(self)
    }

    pub fn subst_uni_var(self, arena: &'hir Arena<'hir>, subs: &Map<UniVarId, Self>) -> Self {
        struct Subs<'a, 'hir> {
            arena: &'hir Arena<'hir>,
            subs: &'a Map<UniVarId, Ty<'hir>>,
        }

        impl<'hir> Folder<'hir, Ty<'hir>> for Subs<'_, 'hir> {
            fn arena(&self) -> &'hir Arena<'hir> {
                self.arena
            }

            fn fold(&mut self, typ: Ty<'hir>) -> Ty<'hir> {
                if let TyKind::Uni(var) = typ.kind()
                    && let Some(&other) = self.subs.get(&var.id)
                {
                    return other;
                }
                typ.fold_with(self)
            }
        }

        Subs { arena, subs }.fold(self)
    }
}

impl<'hir> Substitutable<'hir> for Ty<'hir> {
    type Var = UniVarId;

    fn as_var(&self) -> Option<Self::Var> {
        match self.kind() {
            TyKind::Uni(var) => Some(var.id),
            _ => None,
        }
    }

    fn make_var(arena: &'hir Arena<'hir>, var: Self::Var) -> Self {
        Ty::uni_var(arena, UniVar::new(var, Kind::new(0)))
    }

    fn visit_with<'a, V>(&self, v: &mut V)
    where
        V: Visitor<Self>,
    {
        self.visit_with(v);
    }

    fn fold_with<F>(self, f: &mut F) -> Self
    where
        F: Folder<'hir, Self>,
    {
        self.fold_with(f)
    }
}
