use std::{fmt, hash::Hash};

use base::{
    arena::Interned,
    hash::{IndexSet, Map, Set},
    pp::FormatIterator,
};
use span::{Ident, Span};

use crate::{TyCtxt, resolve::Res};

/// A representation of a type during type inference.
// TODO. interning should canonicalize.
//       don't allow Ty::new(..), make it a method on a ctx.
#[derive(Clone, Copy, Debug)]
pub struct Ty<'t>(Interned<'t, TyKind<'t>>, Span);

impl PartialEq for Ty<'_> {
    fn eq(&self, other: &Self) -> bool {
        self.kind() == other.kind()
    }
}

impl Eq for Ty<'_> {}

impl Hash for Ty<'_> {
    fn hash<H: std::hash::Hasher>(&self, state: &mut H) {
        // Only hash type pointer.
        self.0.hash(state);
    }
}

#[cfg(test)]
mod test {
    use crate::{
        BaseType, TyCtxt,
        typ::{Ty, TyKind},
    };
    use span::Span;

    #[test]
    fn equality() {
        let ctxt = TyCtxt::default();
        let t1 = Ty::new(&ctxt, TyKind::Base(BaseType::Unit), Span::from(0..1));
        let t2 = Ty::new(&ctxt, TyKind::Base(BaseType::Unit), Span::from(1..2));
        assert_eq!(t1, t2);
    }
}

#[derive(Clone, Copy, PartialEq, Eq, Debug)]
pub enum TyKind<'t> {
    /// A base/builtin type.
    Base(syntax::ast::BaseType),

    /// Represents a unification type variable.
    /// For a successfully inferred program, these should all
    /// be substituted away.
    Uni(UniVar),
    /// Represents a type variable that comes from a user-specified
    /// type, such as the `'a` in `'a -> 'a`.
    Var(TypeVar),
    /// Skolem/rigid type variable.
    Skolem(Skolem),

    /// Type represented by a path to a type declaration,
    /// with zero or more arguments.
    App(Res, &'t [Ty<'t>]),

    /// Arrow type `a -> b`.
    Arrow(Ty<'t>, Ty<'t>),
    /// Product of types.
    Tuple(&'t [Ty<'t>]),
    /// Homogeneous vector.
    Vector(Ty<'t>),
}

base::newtype_index! {
    /// Unification variable generated by the elaborator/constraint generator.
    #[derive(PartialOrd, Ord)]
    pub struct UniVarId {}
}

base::newtype_index! {
    /// Unique identifier for a skolem type variable.
    #[derive(PartialOrd, Ord)]
    pub struct SkolemId {}
}

impl fmt::Display for UniVarId {
    fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
        write!(f, "'{}", self.index())
    }
}

#[derive(Clone, Copy, PartialEq, Eq, Hash, Debug)]
pub struct UniVar {
    pub id: UniVarId,
    pub kind: Kind,
}

impl UniVar {
    pub fn new(id: UniVarId, kind: Kind) -> Self {
        Self { id, kind }
    }
}

impl fmt::Display for UniVar {
    fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
        write!(f, "'{}", self.id.index())
    }
}

/// A type variable coming from a user-written polymorphic type.
#[derive(Clone, Copy, PartialEq, Eq, Hash, Debug)]
pub struct TypeVar {
    pub name: Ident,
}

impl TypeVar {
    pub fn new(name: Ident) -> Self {
        Self { name }
    }
}

impl PartialOrd for TypeVar {
    fn partial_cmp(&self, other: &Self) -> Option<std::cmp::Ordering> {
        Some(self.cmp(other))
    }
}

impl Ord for TypeVar {
    fn cmp(&self, other: &Self) -> std::cmp::Ordering {
        self.name.sym.cmp(&other.name.sym)
    }
}

impl fmt::Display for TypeVar {
    fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
        self.name.fmt(f)
    }
}

/// A skolem (or "rigid") type variable.
#[derive(Clone, Copy, Debug)]
pub struct Skolem {
    pub id: SkolemId,
    pub name: Ident,
}

impl Skolem {
    pub fn new(id: SkolemId, name: Ident) -> Self {
        Self { id, name }
    }
}

impl PartialEq for Skolem {
    fn eq(&self, other: &Self) -> bool {
        self.id == other.id
    }
}

impl Eq for Skolem {}

impl PartialOrd for Skolem {
    fn partial_cmp(&self, other: &Self) -> Option<std::cmp::Ordering> {
        Some(self.cmp(other))
    }
}

impl Ord for Skolem {
    fn cmp(&self, other: &Self) -> std::cmp::Ordering {
        self.id.cmp(&other.id)
    }
}

impl fmt::Display for Skolem {
    fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
        write!(f, "#{}:{}", self.name, self.id.index())
    }
}

#[derive(Clone, Copy, PartialEq, Eq, Hash, Debug)]
pub struct Kind {
    /// Kind of term types is arity(0) = *.
    /// Constructor kinds are arity(1) = * -> *, ...
    arity: usize,
}

impl Kind {
    pub fn new(arity: usize) -> Self {
        Kind { arity }
    }
}

impl fmt::Display for Kind {
    fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
        "*".fmt(f)?;
        for _ in 1..self.arity {
            " -> *".fmt(f)?;
        }
        Ok(())
    }
}

pub trait Visitor<T>: Sized {
    fn visit(&mut self, t: T);
}

pub trait Folder<'t, T>: Sized {
    fn ctxt(&self) -> &'t TyCtxt<'t>;

    fn fold(&mut self, t: T) -> T;
}

impl<'t> Ty<'t> {
    #[inline]
    pub fn new(ctxt: &'t TyCtxt<'t>, kind: TyKind<'t>, span: Span) -> Ty<'t> {
        Ty(Interned::new_unchecked(ctxt.arena.alloc(kind)), span)
    }

    #[inline]
    pub fn kind(self) -> &'t TyKind<'t> {
        (self.0).0
    }

    #[inline]
    pub fn span(self) -> Span {
        self.1
    }

    pub fn as_var(self) -> Option<UniVarId> {
        match self.kind() {
            TyKind::Uni(var) => Some(var.id),
            _ => None,
        }
    }

    pub fn visit_with<V>(self, v: &mut V)
    where
        V: Visitor<Self>,
    {
        match *self.kind() {
            TyKind::Base(_) | TyKind::Var(_) | TyKind::Uni(_) | TyKind::Skolem(_) => (),
            TyKind::Vector(t) => v.visit(t),
            TyKind::Arrow(t1, t2) => {
                v.visit(t1);
                v.visit(t2);
            }
            TyKind::App(_, ts) | TyKind::Tuple(ts) => ts.iter().for_each(|&t| v.visit(t)),
        }
    }

    pub fn fold_with<F>(self, f: &mut F) -> Self
    where
        F: Folder<'t, Self>,
    {
        let kind = match *self.kind() {
            TyKind::Base(_) | TyKind::Var(_) | TyKind::Uni(_) | TyKind::Skolem(_) => return self,
            TyKind::App(h, ts) => TyKind::App(
                h,
                f.ctxt()
                    .arena
                    .alloc_from_iter(ts.iter().map(|&t| f.fold(t))),
            ),
            TyKind::Vector(t) => TyKind::Vector(f.fold(t)),
            TyKind::Arrow(t1, t2) => TyKind::Arrow(f.fold(t1), f.fold(t2)),
            TyKind::Tuple(ts) => TyKind::Tuple(
                f.ctxt()
                    .arena
                    .alloc_from_iter(ts.iter().map(|&t| f.fold(t))),
            ),
        };
        if *self.kind() == kind {
            self
        } else {
            Ty::new(f.ctxt(), kind, self.span())
        }
    }

    pub fn tuple<I>(ctxt: &'t TyCtxt<'t>, iter: I, span: Span) -> Self
    where
        I: IntoIterator<Item = Self>,
    {
        Ty::new(ctxt, TyKind::Tuple(ctxt.arena.alloc_from_iter(iter)), span)
    }

    pub fn app<I>(ctxt: &'t TyCtxt<'t>, head: Res, args: I, span: Span) -> Self
    where
        I: IntoIterator<Item = Self>,
    {
        Ty::new(
            ctxt,
            TyKind::App(head, ctxt.arena.alloc_from_iter(args)),
            span,
        )
    }

    pub fn arrow(ctxt: &'t TyCtxt<'t>, source: Self, target: Self) -> Self {
        Ty::new(
            ctxt,
            TyKind::Arrow(source, target),
            source.span().merge(target.span()),
        )
    }

    pub fn n_arrow<I>(ctxt: &'t TyCtxt<'t>, sources: I, target: Self) -> Self
    where
        I: IntoIterator<Item = Self>,
        I::IntoIter: DoubleEndedIterator,
    {
        sources
            .into_iter()
            .rev()
            .fold(target, |acc, source| Ty::arrow(ctxt, source, acc))
    }

    pub fn path(ctxt: &'t TyCtxt<'t>, res: Res, span: Span) -> Self {
        Ty::new(ctxt, TyKind::App(res, &[]), span)
    }

    pub fn type_var(ctxt: &'t TyCtxt<'t>, var: TypeVar) -> Self {
        Ty::new(ctxt, TyKind::Var(var), var.name.span)
    }

    pub fn uni_var(ctxt: &'t TyCtxt<'t>, var: UniVar) -> Self {
        Ty::new(ctxt, TyKind::Uni(var), Span::dummy())
    }

    pub fn eq_alpha(self, other: Self) -> bool {
        #[derive(Default)]
        struct VarMap {
            uni_vars: Map<UniVarId, UniVarId>,
            type_vars: Map<Ident, Ident>,
        }

        fn go<'a>(map: &mut VarMap, lhs: Ty<'a>, rhs: Ty<'a>) -> bool {
            match (*lhs.kind(), *rhs.kind()) {
                (lhs, rhs) if lhs == rhs => true,
                (TyKind::Var(l), TyKind::Var(r)) => match map.type_vars.get(&l.name) {
                    Some(id) => *id == r.name,
                    None => {
                        map.type_vars.insert(l.name, r.name);
                        true
                    }
                },
                (TyKind::Uni(l), TyKind::Uni(r)) => match map.uni_vars.get(&l.id) {
                    Some(id) => *id == r.id,
                    None => {
                        map.uni_vars.insert(l.id, r.id);
                        true
                    }
                },
                (TyKind::Arrow(l1, l2), TyKind::Arrow(r1, r2)) => {
                    go(map, l1, r1) && go(map, l2, r2)
                }
                (TyKind::Vector(l), TyKind::Vector(r)) => go(map, l, r),
                (TyKind::Tuple(ls), TyKind::Tuple(rs)) if ls.len() == rs.len() => {
                    ls.iter().zip(rs).all(|(&l, &r)| go(map, l, r))
                }
                (_, _) => false,
            }
        }

        go(&mut VarMap::default(), self, other)
    }

    pub fn uni_vars(self) -> IndexSet<UniVar> {
        #[derive(Default)]
        struct Vars {
            acc: IndexSet<UniVar>,
        }

        impl<'t> Visitor<Ty<'t>> for Vars {
            fn visit(&mut self, typ: Ty<'t>) {
                if let TyKind::Uni(var) = typ.kind() {
                    self.acc.insert(*var);
                }
                typ.visit_with(self);
            }
        }

        let mut vars = Vars::default();
        vars.visit(self);
        vars.acc
    }

    pub fn type_vars(self) -> Set<TypeVar> {
        #[derive(Default)]
        struct Vars {
            acc: Set<TypeVar>,
        }

        impl<'t> Visitor<Ty<'t>> for Vars {
            fn visit(&mut self, typ: Ty<'t>) {
                if let TyKind::Var(var) = typ.kind() {
                    self.acc.insert(*var);
                }
                typ.visit_with(self);
            }
        }

        let mut vars = Vars::default();
        vars.visit(self);
        vars.acc
    }

    pub fn subst_uni_var(self, ctxt: &'t TyCtxt<'t>, var: UniVar, typ: Self) -> Self {
        struct Subs<'a> {
            ctxt: &'a TyCtxt<'a>,
            var: UniVar,
            typ: Ty<'a>,
        }

        impl<'a> Folder<'a, Ty<'a>> for Subs<'a> {
            fn ctxt(&self) -> &'a TyCtxt<'a> {
                self.ctxt
            }

            fn fold(&mut self, typ: Ty<'a>) -> Ty<'a> {
                if let TyKind::Uni(var) = typ.kind()
                    && var.id == self.var.id
                {
                    self.typ
                } else {
                    typ.fold_with(self)
                }
            }
        }

        Subs { ctxt, var, typ }.fold(self)
    }
}

impl fmt::Display for Ty<'_> {
    fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
        match self.kind() {
            TyKind::Base(b) => b.fmt(f),
            TyKind::Uni(u) => u.fmt(f),
            TyKind::Var(v) => v.fmt(f),
            TyKind::Skolem(s) => s.fmt(f),
            TyKind::App(r, ts) => write!(f, "({r} {})", ts.iter().format(" ")),
            TyKind::Arrow(t1, t2) => write!(f, "({t1} -> {t2})"),
            TyKind::Tuple(ts) => write!(f, "({})", ts.iter().format(" ")),
            TyKind::Vector(t) => write!(f, "[{}]", t),
        }
    }
}
