use std::{
    cell::RefCell,
    fmt,
    hash::{Hash, Hasher},
};

use base::{arena::DroplessArena, hash::IndexSet};

use crate::Span;

thread_local! {
    /// The global interner.
    static INTERNER: RefCell<Interner> = RefCell::default();
}

fn with_interner<F, R>(f: F) -> R
where
    F: FnOnce(&mut Interner) -> R,
{
    INTERNER.with(|x| f(&mut x.borrow_mut()))
}

/// An interned symbol originating from a variable/string in the source code
/// OR generated by type inference.
#[derive(Clone, Copy, PartialEq, Eq, PartialOrd, Ord, Hash)]
pub struct Sym(u32);

impl Sym {
    #[inline]
    pub fn intern(s: &str) -> Self {
        with_interner(|x| x.intern(s))
    }

    pub fn as_str(&self) -> &str {
        with_interner(|x| unsafe { std::mem::transmute::<&str, &str>(x.lookup(*self)) })
    }
}

impl fmt::Debug for Sym {
    fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
        write!(f, "{}({})", self.as_str(), self.0)
    }
}

impl fmt::Display for Sym {
    fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
        self.as_str().fmt(f)
    }
}

/// An identifier has an underlying `Sym` and a `Span`.
#[derive(Clone, Copy)]
pub struct Ident {
    pub sym: Sym,
    pub span: Span,
}

impl Ident {
    #[inline]
    pub const fn new(sym: Sym, span: Span) -> Self {
        Self { sym, span }
    }

    pub fn as_str(&self) -> &str {
        self.sym.as_str()
    }
}

impl PartialEq for Ident {
    fn eq(&self, other: &Self) -> bool {
        // Do not compare by span.
        self.sym == other.sym
    }
}

impl Eq for Ident {}

impl Hash for Ident {
    fn hash<H: Hasher>(&self, state: &mut H) {
        // Do not include span in hash.
        self.sym.hash(state);
    }
}

impl fmt::Debug for Ident {
    fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
        self.as_str().fmt(f)
    }
}

impl fmt::Display for Ident {
    fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
        self.as_str().fmt(f)
    }
}

/// String interner from rustc_span.
#[derive(Default)]
struct Interner {
    arena: DroplessArena,
    strings: IndexSet<&'static str>,
}

impl Interner {
    #[inline]
    fn intern(&mut self, s: &str) -> Sym {
        if let Some(idx) = self.strings.get_index_of(s) {
            return Sym(idx as u32);
        }

        let s = self.arena.alloc_str(s);
        let s: &'static str = unsafe { &*(s as *const str) };
        let (idx, is_new) = self.strings.insert_full(s);
        let sym = Sym(idx as u32);
        debug_assert!(is_new);
        debug_assert_eq!(self.lookup(sym), s);
        debug_assert_eq!(self.intern(s), sym);
        sym
    }

    fn lookup(&self, sym: Sym) -> &str {
        self.strings.get_index(sym.0 as usize).unwrap()
    }
}
